name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - macos-13
          - macos-15

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        if: ${{ matrix.os == 'windows-2025' }}
        with:
          dotnet-version: '9'
      - name: Install WiX & NSIS
        if: ${{ matrix.os == 'windows-2025' }}
        run: |
          dotnet tool install --global wix --version 5.0.2
          wix extension add --global WixToolset.UI.wixext/5.0.2
          choco install nsis
      - name: Install Dependencies
        run: bash deps.sh
        shell: bash
      - name: Configure Project
        run: cmake -B build -DPROJECT_VERSION_SUFFIX=${GITHUB_SHA::7}
        shell: bash
      - name: Build Project
        run: |
          cmake --build build --config Debug --target package
          rm -rf build/package/_CPack_Packages/
        shell: bash
      - name: Archive Package Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: DevGames-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          path: build/package/*
          overwrite: true
          if-no-files-found: error